name: Sync LoTRWiki with Paratranz Project

on:
  schedule:
    - cron: "0 0 1 * *"  # 1st day every month
  workflow_dispatch:

env:
  PARATRANZ_PROJECT_ID: ${{ secrets.PARATRANZ_PROJECT_ID }}
  PARATRANZ_TOKEN: ${{ secrets.PARATRANZ_TOKEN }}
  HUIJI_USERNAME: ${{ secrets.HUIJI_USERNAME }}
  HUIJI_USERID: ${{ secrets.HUIJI_USERID }}
  HUIJI_TOKEN: ${{ secrets.HUIJI_TOKEN }}

jobs:
  sync:
    strategy:
      matrix:
        python-version: [ "3.10" ]
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Python ${{ matrix.python-version }} and Dependents
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install Dependents
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install aiohttp
          pip install aiohttp-retry
          pip install --no-dependencies git+https://github.com/MuXiu1997/ParaTranz-SDK-python.git

      - name: Sync
        run: |
          python -m sync