name: Sync LoTRWiki with Paratranz Project

on:
  schedule:
    - cron: "0 0 1 * *"  # 1st day every month
  workflow_dispatch:

env:
  PARATRANZ_PROJECT_ID: ${{ secrets.PARATRANZ_PROJECT_ID }}
  PARATRANZ_TOKEN: ${{ secrets.PARATRANZ_TOKEN }}
  HUIJI_USERNAME: ${{ secrets.HUIJI_USERNAME }}
  HUIJI_USERID: ${{ secrets.HUIJI_USERID }}
  HUIJI_TOKEN: ${{ secrets.HUIJI_TOKEN }}

jobs:
  sync:
    strategy:
      matrix:
        python-version: [ "3.10" ]
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Poetry  # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
        run: pipx install poetry

      - name: Set Up Python ${{ matrix.python-version }} and Dependents
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
          cache-dependency-path: '**/poetry.lock'

      - name: Initialize Project
        run: poetry install

      - name: Sync
        run: |
          poetry run python sync.py